version: "3.3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD} # Optional

  redis:
    image: "redis:latest"
    volumes:
      - redis_data:/data

volumes:
  redis_data: